# .github/workflows/app.yaml
name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Flake8
        run: |
          python -m pip install flake8

      - name: Check using Flake8
        run: |
          flake8 --exit-zero 

      - name: Update pip
        run: |
          pip3 install --upgrade pip

      - name: Install git
        run: |
          sudo apt-get install git


      - name: Install dependencies
        run: |
          pip3 install num2words discord.py dnspython motor python-dateutil pytz quart python-decouple snowflake-id requests aiohttp sentry_sdk roblox sanic zuid pytest typing_extensions


      - name: Install later dependencies
        run: |
          pip3 install --upgrade reactionmenu jishaku oauth2client gspread_asyncio sentry_sdk[pymongo]

      - name: Run test suite
        run: |
          pytest
